/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  learnSidebar: [{ type: "autogenerated", dirName: "learn" },
    {
      type: "category", 
      label: "Tutorials", 
      collapsed: false, 
            items: [
        {
          type: "doc",
          id: "user/tutorials/vote-extensions/mitigate-frontrunning",
          label: "Mitigating auction Frontrunning",
        },
        {
          type: "link",
          label: "Developer Portal",
          href: "https://tutorials.cosmos.network/tutorials/",
        },
      ],
    }
  ],
  buildSidebar: [{ type: "autogenerated", dirName: "build" },
    {
      type: "category", 
      label: "Tutorials", 
      collapsed: false, 
            items: [
        {
          type: "link",
          label: "Run a Node, API, and CLI",
          href: "https://tutorials.cosmos.network/tutorials/3-run-node/",
        },
        {
          type: "link",
          label: "Run a Cosmos Chain with Ignite CLI",
          href: "https://tutorials.cosmos.network/hands-on-exercise/1-ignite-cli/",
        },
        {
          type: "link",
          label: "Understanding Modules",
          href: "https://tutorials.cosmos.network/tutorials/8-understand-sdk-modules/",
        },
      ],
    }
  ],  
  userSidebar: [
    { type: "autogenerated", dirName: "user" },
  ]
};

module.exports = sidebars;
