name: Test deployment

on:
  pull_request:

jobs:
  test-deploy:
    env:
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
      ALGOLIA_INDEX: ${{ secrets.ALGOLIA_INDEX }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: npm
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: sh ./vue-docs.sh
